### ISSUE TITLE
Support to beta of evernote web

### ISSUE THREAD

**Issue by avol-io** [klauscfhq/tusk#100] opened 2018-07-19 15:02 UTC
From few days i switched on the new beta versione of evernote web.
It's more beautiful and powerful but a lot of features of this app stop to work.

**Comment by dserodio** [comment] 2018-09-10 17:41
Dupe of #88

**Comment by klauscfhq** [comment] 2018-11-06 15:05
Please follow #88

**Closed by klauscfhq** 2018-11-06 15:05 UTC
