### ISSUE TITLE
Feature Request: Text and Icon colors should be theme responsive.

### ISSUE THREAD

**Issue by aryarovana** [klauscfhq/tusk#70] opened 2018-04-21 20:22 UTC
## Description

The most important reason I use tusk is the ability to have a good night mode. but currently, it lacks needed responsiveness in order to make it completely useful, in order to see the text I'm typing I have to change text color for the note I'm making which is not very convenient because I have to change them back again for morning use.

![screen shot 1397-02-02 at 00 46 35 2](https://user-images.githubusercontent.com/7544542/39088419-c2a4a9bc-45c6-11e8-9d44-9f58f5107e70.png)

## Environment

I'm using macOs High Sierra 10.13.4

OS Type: 	Darwin
OS Platform:	darwin
OS Release: 	17.5.0
Architecture: 	x64

## Additional Information

as far as I can tell this issue should be on all operating systems. also, I'd like to help, cause I'm web designer/ developer so I could write the necessary CSS rules but I have no idea how to compile this project. I could also design you a logo and icon if you like me too ;)  thanks for the app.

**Comment by Barafu** [comment] 2018-04-23 11:41
This is a duplicate of #18. In development.

**Comment by klauscfhq** [comment] 2018-04-24 20:45
Feature added on [`bfb835b`](https://github.com/klauscfhq/tusk/commit/bfb835b8339d10e1553c6a5d376d25c29104a477) : )

**Closed by klauscfhq** 2018-04-24 20:45 UTC
Labels: enhancement, feature-request

**Comment by aryarovana** [comment] 2018-04-27 22:11
Thank you. much appreciated. I still offer help needed.
